os: linux
dist: xenial
language: php

notifications:
  on_success: never
  on_failure: change

services:
  - docker

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

env:
  jobs:
    - WP_VERSION=latest
    # - WP_VERSION=5.4
    # - WP_VERSION=5.3
    # - WP_VERSION=5.2
    # - WP_VERSION=5.1

cache:
  directories:
    - /home/travis/build/gruz0/remove-noreferrer/phpcs
    - /home/travis/build/gruz0/remove-noreferrer/rulesets
    - /home/travis/build/gruz0/remove-noreferrer/vendor

before_script:
  - make dockerize_test_database
  - make install_linters
  - make install_wordpress_dev

after_script:
  - make shutdown_test_database

script:
  - make lint
  - make test
