version: '3'
services:
  db:
    image: mariadb:10
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:80"
    volumes:
      - "./tests/integration/docker:/docker"
      - ".:/var/www/html/wp-content/plugins/remove-noreferrer/"
      - "/var/www/html/wp-content/plugins/remove-noreferrer/.data"
      - "/var/www/html/wp-content/plugins/remove-noreferrer/.git"
      - "/var/www/html/wp-content/plugins/remove-noreferrer/.github"
      - "/var/www/html/wp-content/plugins/remove-noreferrer/.wordpress-org"
      - "/var/www/html/wp-content/plugins/remove-noreferrer/build"
      - "/var/www/html/wp-content/plugins/remove-noreferrer/dist"
      - "/var/www/html/wp-content/plugins/remove-noreferrer/tests"
      - "/var/www/html/wp-content/plugins/remove-noreferrer/vendor"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
