name: E2E

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  e2e:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wp_version: ['5.1', '5.2', '5.3', '5.4', '5.5']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: E2E
      run: make e2e_single WP_VERSION=${{ matrix.wp_version }} IS_GITHUB_ACTIONS="1"
