name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  phpunit:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.3']
        wp_version: ['6.7', 'latest']
    steps:
    - name: Stop the GitHub Actions MySQL instance.
      run: sudo service mysql stop
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: xdebug
    - name: Install linters
      run: make setup

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        sudo apt-get install subversion -y

    # Prepare
    - name: Dockerize database
      run: make dockerize_test_database
    - name: Wait for database
      run: make wait_for_database
    - name: Install WordPress
      run: make install_wordpress_dev WP_VERSION=${{ matrix.wp_version }}

    # Tests
    - name: Lint
      run: make lint
    - name: PHPUnit
      run: make test
    - name: Test ZIP
      run: make zip

    # Cleanup
    - name: Shutdown database
      run: make shutdown_test_database
